baseURL = "https://toohuman.io/"
languageCode = "en-gb"
title = "TooHuman - Thoughts on Collective Intelligence"
theme = "PaperMod"

paginate = 5

enableRobotsTXT = true
buildDrafts = true
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "TooHuman"
description = "Postdoc in Autonomous Systems"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Michael Crosscombe"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

    [params.assets]
    favicon = "<link / abs url>"
    favicon16x16 = "<link / abs url>"
    favicon32x32 = "<link / abs url>"
    apple_touch_icon = "<link / abs url>"
    safari_pinned_tab = "<link / abs url>"

    [params.label]
    text = "Home"
    icon = "/apple-touch-icon.png"
    iconHeight = 35

    [params.profileMode]
    enabled = false
    title = "ExampleSite"
    subtitle = "This is subtitle"
    imageUrl = "<img location>"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

    [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Welcome to my blog"

    [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/"

    [[params.socialIcons]]
    name = "stackoverflow"
    url = "https://stackoverflow.com"

    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

    [params.cover]
    hidden = true
    hiddenInList = true
    hiddenInSingle = true

    [params.editPost]
    URL = "https://github.com/toohuman.github.io/content"
    Text = "Suggest Changes"
    appendFilePath = true

    [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1_000
    threshold = 0.4
    minMatchCharLength = 0
    keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "TooHuman"
name = "toohuman.io"
url = "https://toohuman.io"
weight = 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai